### PR TITLE
Add type tag for literals

### PR DESCRIPTION
**Pull request by tidychips**
Adds a `literalType` tag to object literals, so we can actually tell when something was parsed as, say, a decimal.  This was added to as few `primitiveLiteral` options as possible, as it was difficult to tell what's actually used, and what assumptions the mapper makes about existing primitive types.

I can normalize the structure of primitive types so all return an object with the `type` tag and `value` property.

### CODE REVIEW

**Comment by tidychips** [comment]
The `literalType` of `boolean` is added, just in a [different location](https://github.com/lanetix/node-odata-parser/pull/17/files#diff-d7b23f2aacaafb8d8b011f51fbb025a2R615):

```js
type: 'literal',                                        // node type
literalType: typeof l === 'object' ? l.type : typeof l, // the type to interpret the value as
value: typeof l === 'object' ? l.value : l
```

I agree that it would be much cleaner to explicitly set it for all literal types on the rules for the individual cases, though.  I didn't with this PR because:

1. This was a WIP and I submitted this PR (and the other) a little before I should have (sorry!)
1. I'm unsure of how much the `list-query-mapper` depends on the other possible primitive literals (e.g. bytes, int64, etc...) being tagged as `string`

**Comment by wiedld** [comment]
Spoke it over with @pythonesque . We agree that it may be cleaner to add tags for all the primitive literals, where is grammar occurs (at the leaves). Makes it easier to tag everything in the parser with a literalType, even if it's not used yet, such that we'll have a useful error msg in the mapper if anything gets parsed to one of these types.

What do you think?

**Comment by tidychips** [comment]
Agreed that it seems cleaner.  I'll update it and see how well it works with the existing pipeline.

**Comment by tidychips** [comment]
Updated and smoke tested with existing views functionality.  It seems to work well, though null is treated a little weird because:

1. I wasn't able to put a label on the `identifier` subrule in `null`.  I think this is a bug in peg, as I wasn't able to find anything in the docs as to why this wouldn't be valid.
1. There's existing functionality in `list-query-mapper` that assumes null literal values will always be an array.  I could modify this, but felt it was probably out of scope.  Let me know if there's disagreement, as I'm more than happy to change this structure.

This also adds in a REPL, as I found it nice to be able to quickly see the AST generated by the parser for any given input.  I can remove this if desired.

**Pull request merged**
